import type { Metadata } from "next";
import { Plus_Jakarta_Sans as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Suspense } from "react";
import SmoothScroller from "@/components/common/lenis";
import { FloatingNav } from "@/components/common/floating-navbar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems = [
    {
      name: "Home",
      link: "/",
    },
    {
      name: "Services",
      link: "#services",
    },
    {
      name: "Team",
      link: "#team",
    },
  ];
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <Suspense>
          <SmoothScroller />
        </Suspense>
        <div className="mx-auto">
          <FloatingNav navItems={navItems} /> {children}
        </div>
      </body>
    </html>
  );
}
